#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project._004.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLKDONGLUC")]
	public partial class QLKHODataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSYS_NguoiDung(SYS_NguoiDung instance);
    partial void UpdateSYS_NguoiDung(SYS_NguoiDung instance);
    partial void DeleteSYS_NguoiDung(SYS_NguoiDung instance);
    #endregion
		
		public QLKHODataContext() : 
				base(global::Project._004.Models.Properties.Settings.Default.QLKDONGLUCConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLKHODataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLKHODataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLKHODataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLKHODataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SYS_NguoiDung> SYS_NguoiDungs
		{
			get
			{
				return this.GetTable<SYS_NguoiDung>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SYS_NguoiDung")]
	public partial class SYS_NguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_nguoi_dung;
		
		private string _Tai_khoan;
		
		private string _Mat_khau;
		
		private string _Ten_day_du;
		
		private int _ID_trang_thai;
		
		private System.Nullable<int> _ID_nhan_vien;
		
		private System.Nullable<System.DateTime> _Lan_dang_nhap_cuoi;
		
		private System.Nullable<System.TimeSpan> _Thoi_gian_cho;
		
		private string _May_tram;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_nguoi_dungChanging(int value);
    partial void OnID_nguoi_dungChanged();
    partial void OnTai_khoanChanging(string value);
    partial void OnTai_khoanChanged();
    partial void OnMat_khauChanging(string value);
    partial void OnMat_khauChanged();
    partial void OnTen_day_duChanging(string value);
    partial void OnTen_day_duChanged();
    partial void OnID_trang_thaiChanging(int value);
    partial void OnID_trang_thaiChanged();
    partial void OnID_nhan_vienChanging(System.Nullable<int> value);
    partial void OnID_nhan_vienChanged();
    partial void OnLan_dang_nhap_cuoiChanging(System.Nullable<System.DateTime> value);
    partial void OnLan_dang_nhap_cuoiChanged();
    partial void OnThoi_gian_choChanging(System.Nullable<System.TimeSpan> value);
    partial void OnThoi_gian_choChanged();
    partial void OnMay_tramChanging(string value);
    partial void OnMay_tramChanged();
    #endregion
		
		public SYS_NguoiDung()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_nguoi_dung", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_nguoi_dung
		{
			get
			{
				return this._ID_nguoi_dung;
			}
			set
			{
				if ((this._ID_nguoi_dung != value))
				{
					this.OnID_nguoi_dungChanging(value);
					this.SendPropertyChanging();
					this._ID_nguoi_dung = value;
					this.SendPropertyChanged("ID_nguoi_dung");
					this.OnID_nguoi_dungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tai_khoan", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Tai_khoan
		{
			get
			{
				return this._Tai_khoan;
			}
			set
			{
				if ((this._Tai_khoan != value))
				{
					this.OnTai_khoanChanging(value);
					this.SendPropertyChanging();
					this._Tai_khoan = value;
					this.SendPropertyChanged("Tai_khoan");
					this.OnTai_khoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mat_khau", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Mat_khau
		{
			get
			{
				return this._Mat_khau;
			}
			set
			{
				if ((this._Mat_khau != value))
				{
					this.OnMat_khauChanging(value);
					this.SendPropertyChanging();
					this._Mat_khau = value;
					this.SendPropertyChanged("Mat_khau");
					this.OnMat_khauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_day_du", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ten_day_du
		{
			get
			{
				return this._Ten_day_du;
			}
			set
			{
				if ((this._Ten_day_du != value))
				{
					this.OnTen_day_duChanging(value);
					this.SendPropertyChanging();
					this._Ten_day_du = value;
					this.SendPropertyChanged("Ten_day_du");
					this.OnTen_day_duChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_trang_thai", DbType="Int NOT NULL")]
		public int ID_trang_thai
		{
			get
			{
				return this._ID_trang_thai;
			}
			set
			{
				if ((this._ID_trang_thai != value))
				{
					this.OnID_trang_thaiChanging(value);
					this.SendPropertyChanging();
					this._ID_trang_thai = value;
					this.SendPropertyChanged("ID_trang_thai");
					this.OnID_trang_thaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_nhan_vien", DbType="Int")]
		public System.Nullable<int> ID_nhan_vien
		{
			get
			{
				return this._ID_nhan_vien;
			}
			set
			{
				if ((this._ID_nhan_vien != value))
				{
					this.OnID_nhan_vienChanging(value);
					this.SendPropertyChanging();
					this._ID_nhan_vien = value;
					this.SendPropertyChanged("ID_nhan_vien");
					this.OnID_nhan_vienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lan_dang_nhap_cuoi", DbType="DateTime")]
		public System.Nullable<System.DateTime> Lan_dang_nhap_cuoi
		{
			get
			{
				return this._Lan_dang_nhap_cuoi;
			}
			set
			{
				if ((this._Lan_dang_nhap_cuoi != value))
				{
					this.OnLan_dang_nhap_cuoiChanging(value);
					this.SendPropertyChanging();
					this._Lan_dang_nhap_cuoi = value;
					this.SendPropertyChanged("Lan_dang_nhap_cuoi");
					this.OnLan_dang_nhap_cuoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thoi_gian_cho", DbType="Time")]
		public System.Nullable<System.TimeSpan> Thoi_gian_cho
		{
			get
			{
				return this._Thoi_gian_cho;
			}
			set
			{
				if ((this._Thoi_gian_cho != value))
				{
					this.OnThoi_gian_choChanging(value);
					this.SendPropertyChanging();
					this._Thoi_gian_cho = value;
					this.SendPropertyChanged("Thoi_gian_cho");
					this.OnThoi_gian_choChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_May_tram", DbType="NVarChar(200)")]
		public string May_tram
		{
			get
			{
				return this._May_tram;
			}
			set
			{
				if ((this._May_tram != value))
				{
					this.OnMay_tramChanging(value);
					this.SendPropertyChanging();
					this._May_tram = value;
					this.SendPropertyChanged("May_tram");
					this.OnMay_tramChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
