<?xml version="1.0" encoding="utf-8"?><Database Name="QLKDONGLUC" Class="QLKHODataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=203.162.246.102;Initial Catalog=QLKDONGLUC;User ID=sa" SettingsObjectName="Project._004.Models.Properties.Settings" SettingsPropertyName="QLKDONGLUCConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SYS_NguoiDung" Member="SYS_NguoiDungs">
    <Type Name="SYS_NguoiDung">
      <Column Name="ID_nguoi_dung" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Tai_khoan" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Mat_khau" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Ten_day_du" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ID_trang_thai" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_nhan_vien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Lan_dang_nhap_cuoi" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Thoi_gian_cho" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="May_tram" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="CAT_NhanVien_SYS_NguoiDung" Member="CAT_NhanVien" ThisKey="ID_nhan_vien" OtherKey="ID_nhan_vien" Type="CAT_NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CAT_NhanVien" Member="CAT_NhanViens">
    <Type Name="CAT_NhanVien">
      <Column Name="ID_nhan_vien" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ho_dem" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Gioi_tinh" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ngay_sinh" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CMND" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Ngay_cap" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Noi_cap" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Dien_thoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Dia_chi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Trang_thai" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ID_phong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CAT_NhanVien_SYS_NguoiDung" Member="SYS_NguoiDungs" ThisKey="ID_nhan_vien" OtherKey="ID_nhan_vien" Type="SYS_NguoiDung" />
    </Type>
  </Table>
  <Table Name="dbo.SYS_VaiTro" Member="SYS_VaiTros">
    <Type Name="SYS_VaiTro">
      <Column Name="ID_vai_tro" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ten_vai_tro" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ID_cha" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Mo_ta" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>