#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project._004.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLKDONGLUC")]
	public partial class QLKHODataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSYS_NguoiDung(SYS_NguoiDung instance);
    partial void UpdateSYS_NguoiDung(SYS_NguoiDung instance);
    partial void DeleteSYS_NguoiDung(SYS_NguoiDung instance);
    partial void InsertCAT_NhanVien(CAT_NhanVien instance);
    partial void UpdateCAT_NhanVien(CAT_NhanVien instance);
    partial void DeleteCAT_NhanVien(CAT_NhanVien instance);
    partial void InsertSYS_VaiTro(SYS_VaiTro instance);
    partial void UpdateSYS_VaiTro(SYS_VaiTro instance);
    partial void DeleteSYS_VaiTro(SYS_VaiTro instance);
    #endregion
		
		public QLKHODataContext() : 
				base(global::Project._004.Models.Properties.Settings.Default.QLKDONGLUCConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLKHODataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLKHODataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLKHODataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLKHODataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SYS_NguoiDung> SYS_NguoiDungs
		{
			get
			{
				return this.GetTable<SYS_NguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<CAT_NhanVien> CAT_NhanViens
		{
			get
			{
				return this.GetTable<CAT_NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<SYS_VaiTro> SYS_VaiTros
		{
			get
			{
				return this.GetTable<SYS_VaiTro>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SYS_NguoiDung")]
	public partial class SYS_NguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_nguoi_dung;
		
		private string _Tai_khoan;
		
		private string _Mat_khau;
		
		private string _Ten_day_du;
		
		private int _ID_trang_thai;
		
		private System.Nullable<int> _ID_nhan_vien;
		
		private System.Nullable<System.DateTime> _Lan_dang_nhap_cuoi;
		
		private System.Nullable<System.TimeSpan> _Thoi_gian_cho;
		
		private string _May_tram;
		
		private EntityRef<CAT_NhanVien> _CAT_NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_nguoi_dungChanging(int value);
    partial void OnID_nguoi_dungChanged();
    partial void OnTai_khoanChanging(string value);
    partial void OnTai_khoanChanged();
    partial void OnMat_khauChanging(string value);
    partial void OnMat_khauChanged();
    partial void OnTen_day_duChanging(string value);
    partial void OnTen_day_duChanged();
    partial void OnID_trang_thaiChanging(int value);
    partial void OnID_trang_thaiChanged();
    partial void OnID_nhan_vienChanging(System.Nullable<int> value);
    partial void OnID_nhan_vienChanged();
    partial void OnLan_dang_nhap_cuoiChanging(System.Nullable<System.DateTime> value);
    partial void OnLan_dang_nhap_cuoiChanged();
    partial void OnThoi_gian_choChanging(System.Nullable<System.TimeSpan> value);
    partial void OnThoi_gian_choChanged();
    partial void OnMay_tramChanging(string value);
    partial void OnMay_tramChanged();
    #endregion
		
		public SYS_NguoiDung()
		{
			this._CAT_NhanVien = default(EntityRef<CAT_NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_nguoi_dung", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_nguoi_dung
		{
			get
			{
				return this._ID_nguoi_dung;
			}
			set
			{
				if ((this._ID_nguoi_dung != value))
				{
					this.OnID_nguoi_dungChanging(value);
					this.SendPropertyChanging();
					this._ID_nguoi_dung = value;
					this.SendPropertyChanged("ID_nguoi_dung");
					this.OnID_nguoi_dungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tai_khoan", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Tai_khoan
		{
			get
			{
				return this._Tai_khoan;
			}
			set
			{
				if ((this._Tai_khoan != value))
				{
					this.OnTai_khoanChanging(value);
					this.SendPropertyChanging();
					this._Tai_khoan = value;
					this.SendPropertyChanged("Tai_khoan");
					this.OnTai_khoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mat_khau", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Mat_khau
		{
			get
			{
				return this._Mat_khau;
			}
			set
			{
				if ((this._Mat_khau != value))
				{
					this.OnMat_khauChanging(value);
					this.SendPropertyChanging();
					this._Mat_khau = value;
					this.SendPropertyChanged("Mat_khau");
					this.OnMat_khauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_day_du", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ten_day_du
		{
			get
			{
				return this._Ten_day_du;
			}
			set
			{
				if ((this._Ten_day_du != value))
				{
					this.OnTen_day_duChanging(value);
					this.SendPropertyChanging();
					this._Ten_day_du = value;
					this.SendPropertyChanged("Ten_day_du");
					this.OnTen_day_duChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_trang_thai", DbType="Int NOT NULL")]
		public int ID_trang_thai
		{
			get
			{
				return this._ID_trang_thai;
			}
			set
			{
				if ((this._ID_trang_thai != value))
				{
					this.OnID_trang_thaiChanging(value);
					this.SendPropertyChanging();
					this._ID_trang_thai = value;
					this.SendPropertyChanged("ID_trang_thai");
					this.OnID_trang_thaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_nhan_vien", DbType="Int")]
		public System.Nullable<int> ID_nhan_vien
		{
			get
			{
				return this._ID_nhan_vien;
			}
			set
			{
				if ((this._ID_nhan_vien != value))
				{
					if (this._CAT_NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_nhan_vienChanging(value);
					this.SendPropertyChanging();
					this._ID_nhan_vien = value;
					this.SendPropertyChanged("ID_nhan_vien");
					this.OnID_nhan_vienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lan_dang_nhap_cuoi", DbType="DateTime")]
		public System.Nullable<System.DateTime> Lan_dang_nhap_cuoi
		{
			get
			{
				return this._Lan_dang_nhap_cuoi;
			}
			set
			{
				if ((this._Lan_dang_nhap_cuoi != value))
				{
					this.OnLan_dang_nhap_cuoiChanging(value);
					this.SendPropertyChanging();
					this._Lan_dang_nhap_cuoi = value;
					this.SendPropertyChanged("Lan_dang_nhap_cuoi");
					this.OnLan_dang_nhap_cuoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thoi_gian_cho", DbType="Time")]
		public System.Nullable<System.TimeSpan> Thoi_gian_cho
		{
			get
			{
				return this._Thoi_gian_cho;
			}
			set
			{
				if ((this._Thoi_gian_cho != value))
				{
					this.OnThoi_gian_choChanging(value);
					this.SendPropertyChanging();
					this._Thoi_gian_cho = value;
					this.SendPropertyChanged("Thoi_gian_cho");
					this.OnThoi_gian_choChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_May_tram", DbType="NVarChar(200)")]
		public string May_tram
		{
			get
			{
				return this._May_tram;
			}
			set
			{
				if ((this._May_tram != value))
				{
					this.OnMay_tramChanging(value);
					this.SendPropertyChanging();
					this._May_tram = value;
					this.SendPropertyChanged("May_tram");
					this.OnMay_tramChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CAT_NhanVien_SYS_NguoiDung", Storage="_CAT_NhanVien", ThisKey="ID_nhan_vien", OtherKey="ID_nhan_vien", IsForeignKey=true)]
		public CAT_NhanVien CAT_NhanVien
		{
			get
			{
				return this._CAT_NhanVien.Entity;
			}
			set
			{
				CAT_NhanVien previousValue = this._CAT_NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._CAT_NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CAT_NhanVien.Entity = null;
						previousValue.SYS_NguoiDungs.Remove(this);
					}
					this._CAT_NhanVien.Entity = value;
					if ((value != null))
					{
						value.SYS_NguoiDungs.Add(this);
						this._ID_nhan_vien = value.ID_nhan_vien;
					}
					else
					{
						this._ID_nhan_vien = default(Nullable<int>);
					}
					this.SendPropertyChanged("CAT_NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CAT_NhanVien")]
	public partial class CAT_NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_nhan_vien;
		
		private string _Ho_dem;
		
		private string _Ten;
		
		private int _Gioi_tinh;
		
		private System.DateTime _Ngay_sinh;
		
		private string _CMND;
		
		private System.Nullable<System.DateTime> _Ngay_cap;
		
		private string _Noi_cap;
		
		private string _Dien_thoai;
		
		private string _Dia_chi;
		
		private string _Email;
		
		private bool _Trang_thai;
		
		private System.Nullable<int> _ID_phong;
		
		private EntitySet<SYS_NguoiDung> _SYS_NguoiDungs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_nhan_vienChanging(int value);
    partial void OnID_nhan_vienChanged();
    partial void OnHo_demChanging(string value);
    partial void OnHo_demChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnGioi_tinhChanging(int value);
    partial void OnGioi_tinhChanged();
    partial void OnNgay_sinhChanging(System.DateTime value);
    partial void OnNgay_sinhChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnNgay_capChanging(System.Nullable<System.DateTime> value);
    partial void OnNgay_capChanged();
    partial void OnNoi_capChanging(string value);
    partial void OnNoi_capChanged();
    partial void OnDien_thoaiChanging(string value);
    partial void OnDien_thoaiChanged();
    partial void OnDia_chiChanging(string value);
    partial void OnDia_chiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnTrang_thaiChanging(bool value);
    partial void OnTrang_thaiChanged();
    partial void OnID_phongChanging(System.Nullable<int> value);
    partial void OnID_phongChanged();
    #endregion
		
		public CAT_NhanVien()
		{
			this._SYS_NguoiDungs = new EntitySet<SYS_NguoiDung>(new Action<SYS_NguoiDung>(this.attach_SYS_NguoiDungs), new Action<SYS_NguoiDung>(this.detach_SYS_NguoiDungs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_nhan_vien", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_nhan_vien
		{
			get
			{
				return this._ID_nhan_vien;
			}
			set
			{
				if ((this._ID_nhan_vien != value))
				{
					this.OnID_nhan_vienChanging(value);
					this.SendPropertyChanging();
					this._ID_nhan_vien = value;
					this.SendPropertyChanged("ID_nhan_vien");
					this.OnID_nhan_vienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ho_dem", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ho_dem
		{
			get
			{
				return this._Ho_dem;
			}
			set
			{
				if ((this._Ho_dem != value))
				{
					this.OnHo_demChanging(value);
					this.SendPropertyChanging();
					this._Ho_dem = value;
					this.SendPropertyChanged("Ho_dem");
					this.OnHo_demChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gioi_tinh", DbType="Int NOT NULL")]
		public int Gioi_tinh
		{
			get
			{
				return this._Gioi_tinh;
			}
			set
			{
				if ((this._Gioi_tinh != value))
				{
					this.OnGioi_tinhChanging(value);
					this.SendPropertyChanging();
					this._Gioi_tinh = value;
					this.SendPropertyChanged("Gioi_tinh");
					this.OnGioi_tinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay_sinh", DbType="DateTime NOT NULL")]
		public System.DateTime Ngay_sinh
		{
			get
			{
				return this._Ngay_sinh;
			}
			set
			{
				if ((this._Ngay_sinh != value))
				{
					this.OnNgay_sinhChanging(value);
					this.SendPropertyChanging();
					this._Ngay_sinh = value;
					this.SendPropertyChanged("Ngay_sinh");
					this.OnNgay_sinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="VarChar(50)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay_cap", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngay_cap
		{
			get
			{
				return this._Ngay_cap;
			}
			set
			{
				if ((this._Ngay_cap != value))
				{
					this.OnNgay_capChanging(value);
					this.SendPropertyChanging();
					this._Ngay_cap = value;
					this.SendPropertyChanged("Ngay_cap");
					this.OnNgay_capChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Noi_cap", DbType="NVarChar(50)")]
		public string Noi_cap
		{
			get
			{
				return this._Noi_cap;
			}
			set
			{
				if ((this._Noi_cap != value))
				{
					this.OnNoi_capChanging(value);
					this.SendPropertyChanging();
					this._Noi_cap = value;
					this.SendPropertyChanged("Noi_cap");
					this.OnNoi_capChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dien_thoai", DbType="NVarChar(50)")]
		public string Dien_thoai
		{
			get
			{
				return this._Dien_thoai;
			}
			set
			{
				if ((this._Dien_thoai != value))
				{
					this.OnDien_thoaiChanging(value);
					this.SendPropertyChanging();
					this._Dien_thoai = value;
					this.SendPropertyChanged("Dien_thoai");
					this.OnDien_thoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dia_chi", DbType="NVarChar(50)")]
		public string Dia_chi
		{
			get
			{
				return this._Dia_chi;
			}
			set
			{
				if ((this._Dia_chi != value))
				{
					this.OnDia_chiChanging(value);
					this.SendPropertyChanging();
					this._Dia_chi = value;
					this.SendPropertyChanged("Dia_chi");
					this.OnDia_chiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trang_thai", DbType="Bit NOT NULL")]
		public bool Trang_thai
		{
			get
			{
				return this._Trang_thai;
			}
			set
			{
				if ((this._Trang_thai != value))
				{
					this.OnTrang_thaiChanging(value);
					this.SendPropertyChanging();
					this._Trang_thai = value;
					this.SendPropertyChanged("Trang_thai");
					this.OnTrang_thaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_phong", DbType="Int")]
		public System.Nullable<int> ID_phong
		{
			get
			{
				return this._ID_phong;
			}
			set
			{
				if ((this._ID_phong != value))
				{
					this.OnID_phongChanging(value);
					this.SendPropertyChanging();
					this._ID_phong = value;
					this.SendPropertyChanged("ID_phong");
					this.OnID_phongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CAT_NhanVien_SYS_NguoiDung", Storage="_SYS_NguoiDungs", ThisKey="ID_nhan_vien", OtherKey="ID_nhan_vien")]
		public EntitySet<SYS_NguoiDung> SYS_NguoiDungs
		{
			get
			{
				return this._SYS_NguoiDungs;
			}
			set
			{
				this._SYS_NguoiDungs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SYS_NguoiDungs(SYS_NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.CAT_NhanVien = this;
		}
		
		private void detach_SYS_NguoiDungs(SYS_NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.CAT_NhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SYS_VaiTro")]
	public partial class SYS_VaiTro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_vai_tro;
		
		private string _Ten_vai_tro;
		
		private System.Nullable<int> _ID_cha;
		
		private string _Mo_ta;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_vai_troChanging(int value);
    partial void OnID_vai_troChanged();
    partial void OnTen_vai_troChanging(string value);
    partial void OnTen_vai_troChanged();
    partial void OnID_chaChanging(System.Nullable<int> value);
    partial void OnID_chaChanged();
    partial void OnMo_taChanging(string value);
    partial void OnMo_taChanged();
    #endregion
		
		public SYS_VaiTro()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_vai_tro", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_vai_tro
		{
			get
			{
				return this._ID_vai_tro;
			}
			set
			{
				if ((this._ID_vai_tro != value))
				{
					this.OnID_vai_troChanging(value);
					this.SendPropertyChanging();
					this._ID_vai_tro = value;
					this.SendPropertyChanged("ID_vai_tro");
					this.OnID_vai_troChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_vai_tro", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Ten_vai_tro
		{
			get
			{
				return this._Ten_vai_tro;
			}
			set
			{
				if ((this._Ten_vai_tro != value))
				{
					this.OnTen_vai_troChanging(value);
					this.SendPropertyChanging();
					this._Ten_vai_tro = value;
					this.SendPropertyChanged("Ten_vai_tro");
					this.OnTen_vai_troChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_cha", DbType="Int")]
		public System.Nullable<int> ID_cha
		{
			get
			{
				return this._ID_cha;
			}
			set
			{
				if ((this._ID_cha != value))
				{
					this.OnID_chaChanging(value);
					this.SendPropertyChanging();
					this._ID_cha = value;
					this.SendPropertyChanged("ID_cha");
					this.OnID_chaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mo_ta", DbType="NVarChar(MAX)")]
		public string Mo_ta
		{
			get
			{
				return this._Mo_ta;
			}
			set
			{
				if ((this._Mo_ta != value))
				{
					this.OnMo_taChanging(value);
					this.SendPropertyChanging();
					this._Mo_ta = value;
					this.SendPropertyChanged("Mo_ta");
					this.OnMo_taChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
